allow_k8s_contexts('polar')
update_settings(max_parallel_updates=1)

local_resource(
    'observability-configmaps',
    'kubectl create configmap observability-tempo-config --from-file=tempo.yml=polar-deployment/docker/platform/tempo/tempo.yml --dry-run=client -o yaml | kubectl apply -f - && '
    'kubectl create configmap observability-mimir-config --from-file=mimir.yml=polar-deployment/docker/platform/mimir/mimir.yml --dry-run=client -o yaml | kubectl apply -f - && '
    'kubectl create configmap observability-alloy-config --from-file=config.alloy=polar-deployment/kubernetes/local/alloy-k8s.alloy --dry-run=client -o yaml | kubectl apply -f - && '
    'kubectl create configmap observability-grafana-datasources --from-file=datasource.yml=polar-deployment/docker/platform/grafana/datasources/datasource.yml --dry-run=client -o yaml | kubectl apply -f - && '
    'kubectl create configmap observability-grafana-dashboards --from-file=polar-deployment/docker/platform/grafana/dashboards --dry-run=client -o yaml | kubectl apply -f - && '
    'kubectl create configmap observability-grafana-config --from-file=grafana.ini=polar-deployment/docker/platform/grafana/grafana.ini --dry-run=client -o yaml | kubectl apply -f -'
)

k8s_yaml('observability.yml')
k8s_resource('grafana', resource_deps=['observability-configmaps'])
k8s_resource('grafana-alloy', resource_deps=['observability-configmaps'])
k8s_resource('mimir', resource_deps=['observability-configmaps'])
k8s_resource('tempo', resource_deps=['observability-configmaps'])
k8s_resource('loki', resource_deps=['observability-configmaps'])

include('../../../config-service/Tiltfile')
include('../../../edge-service/Tiltfile')
include('../../../dispatcher-service/Tiltfile')
include('../../../order-service/Tiltfile')
include('../../../inventory-service/Tiltfile')
include('../../../catalog-service/Tiltfile')
