CREATE TABLE IF NOT EXISTS book (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    isbn VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    created_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_modified_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version INT NOT NULL DEFAULT 0
);

INSERT INTO book (isbn, title, author, price, created_date, last_modified_date, version)
SELECT '1234567890', 'Polar Journey', 'Iorek Polarson', 12.90, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 0
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM book WHERE isbn = '1234567890');
