apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9005"
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: pxloc97/search-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9005
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9005
            initialDelaySeconds: 5
            periodSeconds: 15
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9005
          resources:
            requests:
              memory: "756Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: BPL_JAVA_NMT_ENABLED
              value: "false"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: OTEL_SERVICE_NAME
              value: "search-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://grafana-alloy:4318"
            - name: MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT
              value: "http://grafana-alloy:4318/v1/traces"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "http://grafana-alloy:4318/v1/logs"
            - name: MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT
              value: "http://grafana-alloy:4318/v1/logs"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service"
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://elasticsearch:9200"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "polar-kafka:19092"
          volumeMounts:
            - name: search-service-volume
              mountPath: /workspace/config
            - name: search-service-volume-secret
              mountPath: /workspace/secrets/search-service
              readOnly: true
      volumes:
        - name: search-service-volume
          configMap:
            name: search-service
        - name: search-service-volume-secret
          secret:
            secretName: search-service
