apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
    - protocol: TCP
      targetPort: 9005
      port: 9005
