plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '6.25.0'
}

apply from: '../gradle/java-base.gradle'
apply from: '../gradle/spotless.gradle'
apply from: '../gradle/boot-image.gradle'
apply from: '../gradle/observability.gradle'

description = 'catalog-service'

ext {
    set('springCloudVersion', "2025.1.0")
    set('testcontainersVersion', "1.19.7")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-bus-kafka'
    implementation 'org.springframework.cloud:spring-cloud-stream'
    implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation("com.github.ben-manes.caffeine:caffeine:3.2.4")
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3'
    implementation 'com.mysql:mysql-connector-j'
    implementation 'org.springframework.kafka:spring-kafka'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-test-autoconfigure'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux'
    testImplementation 'org.springframework.boot:spring-boot-webtestclient'
    testImplementation 'org.springframework:spring-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation "org.testcontainers:mysql:${testcontainersVersion}"
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'com.h2database:h2'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.4.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
    }
}
