server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
polar:
  catalogServiceUrl: http://localhost:9001

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      username: user
      password: password
      request-connect-timeout: 2000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    function:
      definition: dispatchOrder;handleInventoryDecision;handleBookCreated;handleBookUpdated;handleBookDeleted
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
        handleInventoryDecision-in-0:
          destination: inventory-events
          group: ${spring.application.name}
        handleBookCreated-in-0:
          destination: book.created
          group: ${spring.application.name}
        handleBookUpdated-in-0:
          destination: book.updated
          group: ${spring.application.name}
        handleBookDeleted-in-0:
          destination: book.deleted
          group: ${spring.application.name}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 500ms
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/polardb_order
    username: user
    password: password
    pool:
      max-size: 40
      initial-size: 20
      max-create-connection-time: 5s
      max-acquire-time: 10s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5433/polardb_order
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/PolarBookshop

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      roles: ADMIN
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


