polar:
  greeting: "Welcome to the catalog from the config server"

spring:
  cloud:
    config:
      bus:
        enabled: false
    function:
      definition: bookCreatedEvents;bookUpdatedEvents;bookDeletedEvents
    stream:
      bindings:
        bookCreatedEvents-out-0:
          destination: book.created
          content-type: application/json
        bookUpdatedEvents-out-0:
          destination: book.updated
          content-type: application/json
        bookDeletedEvents-out-0:
          destination: book.deleted
          content-type: application/json
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/PolarBookshop
