server:
  ssl:
    enabled: ${MTLS_ENABLED:false}
    client-auth: ${BACKEND_MTLS_CLIENT_AUTH:need}
    key-store: ${MTLS_KEY_STORE:}
    key-store-password: ${MTLS_KEY_STORE_PASSWORD:}
    key-store-type: ${MTLS_KEY_STORE_TYPE:PKCS12}
    trust-store: ${MTLS_TRUST_STORE:}
    trust-store-password: ${MTLS_TRUST_STORE_PASSWORD:}
    trust-store-type: ${MTLS_TRUST_STORE_TYPE:PKCS12}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://polar-keycloak:8080}/realms/PolarBookshop
  cloud:
    config:
      bus:
        enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:polar-kafka:19092}
