spring:
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
  cloud:
    config:
      bus:
        enabled: false
    function:
      definition: handleBookCreated;handleBookUpdated;handleBookDeleted
    stream:
      bindings:
        handleBookCreated-in-0:
          destination: book.created
          group: ${spring.application.name}
        handleBookUpdated-in-0:
          destination: book.updated
          group: ${spring.application.name}
        handleBookDeleted-in-0:
          destination: book.deleted
          group: ${spring.application.name}
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
