server:
  port: 9004
  shutdown: graceful

spring:
  application:
    name: inventory-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/PolarBookshop
  cloud:
    config:
      uri: http://localhost:8888
      username: user
      password: password
      request-connect-timeout: 2000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    function:
      definition: reserveStock;releaseStock
    stream:
      bindings:
        reserveStock-in-0:
          destination: order-created-events
          group: ${spring.application.name}
        releaseStock-in-0:
          destination: order-cancelled-events
          group: ${spring.application.name}
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/polardb_inventory
    username: user
    password: password
    pool:
      max-size: 40
      initial-size: 5
      max-create-connection-time: 2s
      max-acquire-time: 5s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5434/polardb_inventory
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      roles: ADMIN
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.locpham.bookstore.inventoryservice: INFO
    com.locpham.bookstore.inventoryservice.adapter.out.persistence: DEBUG
    com.locpham.bookstore.inventoryservice.adapter.in.messaging: INFO
    com.locpham.bookstore.inventoryservice.application.service: INFO
    org.springframework.cloud.stream: INFO
    org.jooq: WARN
