plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '6.25.0'
}

apply from: '../gradle/java-base.gradle'
apply from: '../gradle/spotless.gradle'
apply from: '../gradle/boot-image.gradle'
apply from: '../gradle/observability.gradle'

description = 'edge-service'

ext {
    set('springCloudVersion', "2025.1.0")
    set('testcontainersVersion', "1.19.7")
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'
    implementation(
            'org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j'
    )
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-bus-kafka'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'io.github.resilience4j:resilience4j-micrometer'
    implementation 'org.springframework.session:spring-session-data-redis'
    runtimeOnly("io.netty:netty-resolver-dns-native-macos") {
        artifact {
            classifier = 'osx-aarch_64'
        }
    }

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.cloud:spring-cloud-stream-test-binder'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'com.github.dasniko:testcontainers-keycloak:3.4.0'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
    }
}
