custom_build(
    ref='search-service',
    command='./gradlew bootBuildImage --imageName $EXPECTED_REF',
    deps=['build.gradle', 'src'],
)

k8s_yaml([
    'k8s/deployment.yml',
    'k8s/service.yml',
])

k8s_resource('search-service', port_forwards=['9005'])
